### ISSUE TITLE
Put flask secret key in production.

### ISSUE THREAD

**Issue by BOluokun** [JamesLee-Jones/nlp-timeline-gen#17]
The Heroku server can not currently access the secret key needed by Flask for objects like `session` and `flash()`, this has been causing errors on the web page.

To fix this find a way to store the secret key somewhere that can be accessed in the deploy stage of the pipeline but ensure it is still hidden from the repo (should not be visible in plain text).

Add a test for this!

**Comment by JamesLee-Jones** [comment]
Also remember to fix the typo!

**Comment by JamesLee-Jones** [comment]
@BOluokun I have an idea about how to approach this, we can talk about it later.
